(() => {
  console.log('fired!!');
  
  function logKeyCode(event) {
    // debugger;
    // EVENT IS AN OBJECT THAT IS GENERATED BY ANY EVENT 
    // IT CONTAINS QLL OF THE INFO ABOUT THE EVENT, WHAT
    // TRIGGEREDR IT, WHERE IT OCCURE ON THE PAGE ETC
    console.log(event.keyCode); //match key to audio 

    const currentKey = document.querySelector(`div[data-key="${event.keyCode}"]`);

    if (!currentKey) return;
       //appy the playing class to the current div( the matching keycode)
       currentKey.classList.add('playing');
       
      let currentAudioClip = document.querySelector(`audio[data-key="${event.keyCode}"]`);
      currentAudioClip.currentTime = 0;
      currentAudioClip.play();
}

function removePlayingClass(event) {
  //listen for transition to end, and then remove the playing class from current key
  //i need a transition thato nly fires once so that i oly run this function once
  if (event.propertyName !== "transform") return; 
    //event target is the target of the current event -> in the case the div
    //cuz thats the transitioning element
    console.log('transform transition is done!');
    event.target.classList.remove('playing');
}

const key = Array.from(document.querySelectorAll('.key'));
key.forEach(key => key.addEventListener('transitionend', removePlayingClass));

  //   //IF WE MAKE A SUCCESSFUL MATCH, PLAY MATCHING AUDIO TRACK
  //   //a  ! (bang operator) means not or if this doesnt exist
  //   //prper way to check a false
  //   if (currentAudioClip) {
  //     currentAudioClip.play();
  //   } else {
  //     //THERE IS NO MATCH, SO NO AUDIO WILL PLAY => DO NOTHING
  //     //A RETUREN WILL MAKE A FUNCTION EXIT W/OUT BREAKIGN ANYTHING
  //     return;
  //   }
  
  // }

  // function resetSound(event) {

  //   //need this to reset audio, but onyl if a matching element
  //   //the event has the keycode - i need to make sure i find the media first

  //   //audio has a currentTime property - reset that to 0
  //   //check witha condition statement
  //   let currentAudioClip = document.querySelector(`audio[data-key="${event.keyCode}"]`);
    
  //   if (currentAudioClip) {
  //     currentAudioClip.currentTime = 0; //resets sound to play over
  //   } else {
  //     return;
  //   }
  // }

  //TRY TO GET THE KEYBOARD KEYPRESS EVENTS
  window.addEventListener("keydown", logKeyCode);
  // window.addEventListener("keyup", resetSound);
})();
